### ISSUE TITLE
Performace

### ISSUE THREAD

**Issue by hugohadfield** [pygae/clifford#10]
Hi Alex,

Having seen your issues raised with pyversor (https://github.com/tingelst/pyversor/issues/7) I agree entirely that something should be done to improve the python GA tooling.
@ereide and I work extensively with this library at Cambridge. From our perspective the key advantages that it offers are:
1. Syntax -> Close to the math (minus the operator precedence issues)
2. Distribution -> All the requirements of the package are part of the standard python scientific ecosystem. It does not require a complex build process and is available with pip. This massively reduces the barriers to getting started.

The disadvantage of this library:
1. Performance. As you have previously mentioned the matrix multiplication basis of the library is very inefficient and prevents it from being realistically useful in large applications.

What do you see as the future of this project? Do you intend to continue developing it performance-wise? 
If so, what do you think needs to be done? and how can I help?

**Comment by arsenovic** [comment]
hi, good to hear this!

maybe we could all schedule  a google hangout? to discuss 
*  what everyone is doing
*  what they want/need
* how much resources are available. 

i spoke with @tingelst the other day and it was very helpful. there have been so much work done on  GA implementations, and  i think its good to think before we go coding into the sunset.  ill try to take notes and transcribe the conversions into github, so its on the web.

feel free to email me if you prefer,

**Comment by eric-wieser** [comment]
FYI, [numpy is starting to think seriously about extensible dtypes again](https://youtu.be/fowHwlpGb34?t=19m46s), now that it has funding to support a small team full-time. In the long run, this ought to be a good match for representing GA types efficiently.

**Comment by ereide** [comment]
I second @hugohadfield's comments.

**Comment by arsenovic** [comment]
@eric-wieser , great presentation, thanks for posting this. Nathan's argument that it is more expensive to do nothing, than pay to do something is applicable for adopting  GA as well.  are you a user of clifford? perhaps you could be our ambassador to numpy?

@moble , has done work on  [quaternion](https://github.com/moble/quaternion) dtype package for numpy, so ill link him in here.  

a few ideas 

* i have created a [wiki doc](https://github.com/arsenovic/clifford/wiki/Geometric-Algebra-in-Python) in clifford to document what we might do. please add to it. my thought is to open the design discussion, and get experienced people to look at it.  (maybe we can convince ourselves not to do this!)

* i think a google hangout would go a long way also, perhaps everyone interested could respond with an available time to chat.  

* if this group solidifies, we could create a github organisation  for (numerical) GA python users [GAP]? and move the module and 'spec doc' to the group.

 Chris Doran (@chrisjldoran) has made [arguments](https://web.archive.org/web/20111030110405/http://www.geomerics.com/downloads/agacse_doran_presentation.pdf) at AGACSE for using Haskel as a suitable language for GA. See https://github.com/ga , @lukeburns. not sure if there is any room for collaboration, but thought i would link it in. an interesting feature which we might consider is the lazy evaluation of multivector objects (perhaps realizable through use generators as return types).

**Comment by hugohadfield** [comment]
@arsenovic I think a google hangout is a good idea, maybe tomorrow or the next day? The timezones might be a little tricky to work out, but I'm sure we can arrange something

I definitely agree that it would be great to get GA into numpy, even if it is just a few spaces eg. 3d and 3d conformal GA, hopefully we could use the quaternion dtype package as a starting point

@joanlasenby and @rjw57 might also be interested in following along with updates on this thread too

**Comment by tingelst** [comment]
I am available for a hangout tomorrow, Thursday. I’m busy all Friday.

**Comment by joanlasenby** [comment]
Dear All
  so happy that people are keen to move things forward. 

Alex, Lars -- I am lucky to have Hugo and Eivind working here in Cambridge 
and wanting to engage with you both :-)

 I am taken out Thurs with project presentations, but Hugo can update me 
when we meet on Friday. Best Joan

>I am available for a hangout tomorrow, Thursday. I'm busy all Friday. 
>
>

-- 
Dr Joan Lasenby
Reader in Signal Processing
Signal Processing Group
Cambridge University Engineering Department
Trumpington Street
Cambridge CB2 1PZ
UK
Tel +441223 332639
Fax +441223 332662
Email: jl221@cam.ac.uk
Web: www-sigproc.eng.cam.ac.uk/~jl


Trinity College
Trinity Street
Cambridge CB2 1TQ
Tel +441223 338451

**Comment by moble** [comment]
I'll be available tomorrow any time after about 8:30AM US Eastern time (but I've got infant twins to get off to daycare, so minor delays may occur).  Just let me know if a hangout is happening.

**Comment by eric-wieser** [comment]
> are you a user of clifford? perhaps you could be our ambassador to numpy?

I'm afraid I'm not. I think I came across this package after @moble's quaternion module found a numpy bug, and ended up doing a quick search for whether anyone else had tried the custom dtype route.

You might want to keep an eye on the `numpy-discussion` [mailing list](https://www.scipy.org/scipylib/mailing-lists.html) so that you can poke the right people when @njsmith gets his full-time numpy development team at BIDS.

**Comment by hugohadfield** [comment]
So maybe 10:00 AM EST = 3:00 PM GMT for a hangout? I'm pretty free all day

**Comment by arsenovic** [comment]
ok, everyone, Here is a  [link to the google hangout ](https://calendar.google.com/calendar/hosted/810lab.com/event?action=TEMPLATE&tmeid=NWw3Zm1pZDY0cW1vdWFlNmhnOThha2pjMDMgYWxleEA4MTBsYWIuY29t&tmsrc=alex%40810lab.com)at 10am EST (in ~2hrs) . 

sorry for last minuteness, see you there.

**Comment by chrisjldoran** [comment]
Won't be able to make this one, but will catch up with people afterwards.

**Comment by arsenovic** [comment]
here is summary of meeting. feel free to add things i missed. 

https://github.com/arsenovic/clifford/wiki/Meeting-11-16-17

**Comment by moble** [comment]
The matrix multiplication issue @hugohadfield brought up was bugging me, so I made [this notebook](https://gist.github.com/moble/119c740e204a31dd0920ba592f465b4d).  I reckon each multiplication in 5d should take around 40 microseconds on a modern chip with the right matrix-multiplication library.  That's slower than I expected, but I had forgotten that the multiplication array is of size `8**n` (I thought it was just `4**n`).  But [it could be more like a millisecond with the wrong backend](http://markus-beuckelmann.de/blog/boosting-numpy-blas.html).

Another significant finding is that `a @ mt @ b` appears to be ~30% faster than `np.dot(a, np.dot(mt, b))` for these arrays, so that would be an easy (but small) speedup.

Finally, it occurs to me that transitioning to the bit-twiddling form of these products could be done without actually changing how the data are stored, meaning that nothing except the product functions (`__mul__`, etc.) would need to change.  It still probably wouldn't be the most efficient storage possible, but you can figure out the bit representation of the blade pretty readily from the index in the `.value` array (though it might be more efficient to just figure that out once and store it in an array, depending on how `clifford` actually stores things).  That's all you really need to move over to the other kind of multiplication; just loop over the `.value.nonzero()` indices.  It seems about as painless as this kind of thing could be, and once you've got that sorted out, you could go back and change the storage to be more efficient if you still have the motivation.

**Comment by hugohadfield** [comment]
I am gonna close this issue as I think for the most part the biggest performance problems of this project have been solved! :) there are still areas to work (large algebra initialisation times etc) but I think they can be dealt with elsewhere!
