### ISSUE TITLE
problem with adding to numpy.float64, ufunc issue?

### ISSUE THREAD

**Issue by arsenovic** [pygae/clifford#2]
i am working on changing the operators ([on this branch](https://github.com/arsenovic/clifford/tree/operatorchange))   to match those in galgebra: ie   `&`->`*` and from `*`->`|`

however, i am getting some strange behavior which i dont undertand, which seems to be related to some operator overloads with numpy dtypes. it appears as though the `float64.__add__` is taking precedence over cliffords `MultiVector.__radd__`. not sure why the operator changes created this problem. 

@moble, @rkern  perhaps you all have some ideas on how to solve  this?

here is demo of error, 
  https://gist.github.com/13b0ee10dde76817c79aab567b682efa

**Comment by rkern** [comment]
The left operand gets the first shot at implementing the operation. Only if it fails does the right operand attempt with its `__radd__` method. Because `MultiVector` implements the `Sequence` interface, `np.asarray()` knows how to convert it to a numpy array via `np.asarray()`. The numpy scalar types will attempt to convert the other operand to a numpy array via `np.asarray()`. Since this succeeds, `np.float64.__add__()` succeeds, and `MultiVector.__radd__()` does not get a chance to run.

I don't have a good idea offhand how to get around this.

**Comment by arsenovic** [comment]
thanks very much for the info. 

 is it clear to you that the operator change would cause this? the `exp()` function  operating on a `MultiVector` now fails also, which i suspect is related.

a similar question is raised in this [SO post](http://stackoverflow.com/questions/22632937/how-to-make-numpy-overloading-of-add-independent-on-operand-order).  after looking at their suggestions the `__array_priority__ ` does not work, but `__array_wrap__` does. however this  hook seems to be after the numpy  `__add__` has happened...

they also suggest to subclassing `ndarray`.  however, i am not sure that i have the time/ability to make this change to the whole class, or to decide whether it is a good idea.

**Comment by arsenovic** [comment]
so if the left hand operator fails, the right operand attempt with its __radd__ method, then  would it be possible to make the ufunc  'fail' by doing something in `__array_prepare__`

**Comment by arsenovic** [comment]
https://github.com/arsenovic/clifford/commit/bd3bb72454131da60ca19909124901229b9c2086 . . . embarrasing

**Comment by hugohadfield** [comment]
@arsenovic is this now fixed or still a problem?

**Comment by arsenovic** [comment]
i think we can close
